# Generated by Django 5.2 on 2026-06-17 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('friendly', 'Friendly')], max_length=10)),
                ('length_min', models.PositiveIntegerField()),
                ('lentgh_max', models.PositiveIntegerField()),
                ('num_actionable_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(8)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('course_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.courselead')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spec', models.TextField()),
                ('rubric', models.TextField()),
                ('moderation_algorithm', models.CharField(choices=[('linear', 'Linear'), ('z-score', 'Z-Score')], max_length=10)),
                ('prompt', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('feedback_spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.feedbackspec')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(8)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_cid', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(8)])),
                ('grade', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('moderated_grade', models.FloatField(blank=True, null=True)),
                ('moderated_feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assignment')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marker')),
            ],
            options={
                'unique_together': {('assignment', 'marker')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_grade', models.FloatField(blank=True, null=True)),
                ('marker_feedback', models.TextField(blank=True, null=True)),
                ('llm_feedback', models.TextField(blank=True, null=True)),
                ('approved_feedback', models.TextField(blank=True, null=True)),
                ('marker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.marker')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.submission')),
            ],
            options={
                'unique_together': {('submission', 'marker')},
            },
        ),
    ]
